# -*- coding: utf-8 -*-
"""Train_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxMhahXFEA-AeDq-SgeeX11ry7TnovWO
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import io
import joblib


from google.colab import files
uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded['creditcard.csv']))

X = df.drop('Class', axis=1)
y = df['Class']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3)
model = LogisticRegression()
model.fit(X_train, y_train)

joblib.dump(model, "fraud_model.pkl")
joblib.dump(scaler, "scaler.pkl")